# Website settings
url: "https://robertspurlin.com"

# Internal nav
nav:
  main:
    projects: "/projects"
    blog: "/blog"

  blog:
    all: "/blog"
    popular: "/blog/popular"
    tags: "/blog/tags"
    rss: "/feed.xml"

# Bio settings
name: "Robert Spurlin"
description: "The home page of Robert Spurlin, Full-Stack Developer for Quaver Music, Middle Tennessee State University, and Titan Web Marketing Solutions."
thumbnail_path: "profile-photos/robert_spurlin.jpg"
website_repo_url: "https://github.com/robertspurlin/robertspurlin.com"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/spurlinrobert"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/robertspurlin/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:robertspurlin1996@gmail.com"
    label: "Email"
    value: "robertspurlin1996@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 5
paginate_path: "/blog/page:num"
permalink: "/blog/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: robertspurlin/robertspurlin.com

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
